include: https://api.choerodon.com.cn/devops/v1/projects/245961945059782656/ci_contents/pipelines/b7d651ef-c267-4f36-bb0e-aa85a8769b92/content.yaml

#include: https://api.choerodon.com.cn/devops/v1/projects/2183/ci_contents/pipelines/8c055860-eae2-4ef0-8f2a-cebeba9eb914/content.yaml